# Generated by Django 3.0.6 on 2020-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='googleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('Username', models.CharField(max_length=12000)),
                ('Expiry_time', models.CharField(max_length=20)),
                ('access_token', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('RoleId', models.IntegerField(default=1)),
                ('RoleName', models.CharField(default=None, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=12000)),
                ('FirstName', models.CharField(default=None, max_length=50)),
                ('SecondName', models.CharField(default=None, max_length=50)),
                ('RoleId', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('IsLoggedin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
