# Generated by Django 3.0.6 on 2020-08-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidGooglemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(db_column='Username', max_length=12000)),
                ('expiry_time', models.CharField(db_column='Expiry_time', max_length=20)),
                ('access_token', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Android_googlemodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AndroidRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.IntegerField(db_column='RoleId')),
                ('roletype', models.CharField(db_column='RoleType', max_length=50)),
            ],
            options={
                'db_table': 'Android_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderAccesstoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_accesstoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('redirect_uris', models.TextField()),
                ('client_type', models.CharField(max_length=32)),
                ('authorization_grant_type', models.CharField(max_length=32)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('skip_authorization', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('redirect_uri', models.CharField(max_length=255)),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('code_challenge', models.CharField(max_length=128)),
                ('code_challenge_method', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'oauth2_provider_grant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderRefreshtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('revoked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth2_provider_refreshtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AndroidUsers',
            fields=[
                ('password', models.CharField(max_length=255)),
                ('last_login', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('logged_in', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('roleid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Android.AndroidRoles')),
            ],
            options={
                'db_table': 'Android_users',
                'managed': False,
            },
        ),
    ]
