# Generated by Django 3.0.6 on 2020-08-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Android', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='androidusers',
            table='AndroidUsers',
        ),
    ]
