# Generated by Django 3.0.6 on 2020-05-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Android', '0003_auto_20200506_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='pasword',
        ),
    ]
