# Generated by Django 3.0.6 on 2020-08-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Android', '0003_auto_20200801_1150'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='androidusers',
            table='Android_users',
        ),
    ]
