# Generated by Django 3.0.6 on 2020-05-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Android', '0004_auto_20200506_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='FirstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='SecondName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='IsLoggedin',
            new_name='logged_in',
        ),
        migrations.RemoveField(
            model_name='users',
            name='RoleId',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pasword',
        ),
        migrations.AddField(
            model_name='users',
            name='roleid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roles',
            name='RoleId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=12000),
        ),
    ]
